CREATE TABLE buyers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  market TEXT NOT NULL,
  city TEXT,
  category TEXT,
  website TEXT,
  linkedin_url TEXT,
  contact_name TEXT,
  contact_title TEXT,
  contact_email TEXT,
  contact_phone TEXT,
  contact_linkedin TEXT,
  score_strategic_fit INTEGER,
  score_purchasing_power INTEGER,
  score_accessibility INTEGER,
  score_total INTEGER,
  priority_tier TEXT DEFAULT 'B',
  certifications_required TEXT,
  annual_import_volume TEXT,
  current_suppliers TEXT,
  pain_points TEXT,
  status TEXT DEFAULT 'not_contacted',
  assigned_to TEXT DEFAULT 'Danny',
  source TEXT,
  notes TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE suppliers (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT,
  state TEXT,
  category TEXT,
  website TEXT,
  linkedin_url TEXT,
  contact_name TEXT,
  contact_title TEXT,
  contact_email TEXT,
  contact_phone TEXT,
  certifications TEXT,
  export_markets TEXT,
  export_experience_years INTEGER,
  moq TEXT,
  lead_time_days INTEGER,
  sample_available INTEGER DEFAULT 1,
  score_quality INTEGER,
  score_certifications INTEGER,
  score_export_readiness INTEGER,
  score_reliability INTEGER,
  score_total INTEGER,
  readiness_tier TEXT DEFAULT 'B',
  status TEXT DEFAULT 'new',
  assigned_to TEXT DEFAULT 'Neha',
  source TEXT,
  notes TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  common_names TEXT,
  category TEXT,
  form TEXT,
  key_markets TEXT,
  typical_price_range TEXT,
  notes TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE buyer_products (
  id TEXT PRIMARY KEY,
  buyer_id TEXT REFERENCES buyers(id),
  product_id TEXT REFERENCES products(id),
  interest_level TEXT DEFAULT 'medium',
  volume_needed TEXT,
  spec_requirements TEXT,
  notes TEXT
);
CREATE TABLE supplier_products (
  id TEXT PRIMARY KEY,
  supplier_id TEXT REFERENCES suppliers(id),
  product_id TEXT REFERENCES products(id),
  specification TEXT,
  price_per_kg TEXT,
  capacity_per_month TEXT,
  certifications TEXT,
  notes TEXT
);
CREATE TABLE opportunities (
  id TEXT PRIMARY KEY,
  buyer_id TEXT REFERENCES buyers(id),
  supplier_id TEXT REFERENCES suppliers(id),
  product_id TEXT REFERENCES products(id),
  market TEXT,
  value_estimate REAL,
  probability INTEGER,
  opportunity_score INTEGER,
  expected_close_date TEXT,
  status TEXT DEFAULT 'open',
  next_action TEXT,
  next_action_date TEXT,
  assigned_to TEXT DEFAULT 'Danny',
  notes TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE outreach_log (
  id TEXT PRIMARY KEY,
  buyer_id TEXT REFERENCES buyers(id),
  opportunity_id TEXT REFERENCES opportunities(id),
  channel TEXT,
  direction TEXT,
  subject TEXT,
  body TEXT,
  sent_by TEXT,
  gmail_message_id TEXT,
  gmail_thread_id TEXT,
  response_received INTEGER DEFAULT 0,
  response_summary TEXT,
  follow_up_due TEXT,
  notes TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE outcomes (
  id TEXT PRIMARY KEY,
  opportunity_id TEXT REFERENCES opportunities(id),
  outcome_type TEXT,
  revenue_generated REAL,
  description TEXT,
  why_won TEXT,
  why_lost TEXT,
  lessons_learned TEXT,
  follow_up_date TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);